# Generated by Django 4.2.6 on 2023-10-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(default='Perfect Product', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vendor', models.CharField(max_length=30)),
                ('amount', models.PositiveIntegerField()),
                ('delivery_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[('FR', 'Fruit'), ('MT', 'Meat'), ('AL', 'Alcohol')], max_length=2)),
            ],
        ),
    ]
