# Generated by Django 4.2.6 on 2023-10-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendors',
        ),
        migrations.AddField(
            model_name='customer',
            name='product',
            field=models.ManyToManyField(to='ecoshop.product'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='product',
            field=models.ManyToManyField(to='ecoshop.product'),
        ),
        migrations.AlterModelTable(
            name='customerreview',
            table='ecoshop_customer_reviews',
        ),
        migrations.AlterModelTable(
            name='productreview',
            table='ecoshop_product_reviews',
        ),
        migrations.AlterModelTable(
            name='vendorreview',
            table='ecoshop_vendor_reviews',
        ),
    ]
