# Generated by Django 4.2.6 on 2023-10-16 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='vendor',
        ),
    ]
