# Generated by Django 4.2.6 on 2023-10-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0002_rename_delivery_date_product_date_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerrating',
            table='customer_rating',
        ),
        migrations.AlterModelTable(
            name='vendorrating',
            table='vendor_rating',
        ),
    ]
