# Generated by Django 4.2.6 on 2023-10-26 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0002_alter_category_options_remove_product_customers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='product',
            new_name='products',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='product',
            new_name='products',
        ),
    ]
