# Generated by Django 4.2.6 on 2023-10-16 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0002_vendor_remove_product_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='foundation_year',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
