# Generated by Django 4.2.6 on 2023-10-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0003_alter_customerrating_table_alter_vendorrating_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customerrating',
            table='ecoshop_customer_rating',
        ),
        migrations.AlterModelTable(
            name='vendorrating',
            table='echoshop_vendor_rating',
        ),
    ]
