# Generated by Django 4.2.6 on 2023-10-18 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0004_alter_customerrating_table_alter_vendorrating_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vendorrating',
            table='ecoshop_vendor_rating',
        ),
    ]
