# Generated by Django 4.2.6 on 2023-11-20 08:13

import django.core.validators
from django.db import migrations, models
import ecoshop.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0005_category_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(default='image_not_found.jpg', upload_to=ecoshop.models.user_dir_photo),
        ),
        migrations.AddField(
            model_name='customer',
            name='photo',
            field=models.ImageField(default='image_not_found.jpg', upload_to=ecoshop.models.user_dir_photo),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='image_not_found.jpg', upload_to=ecoshop.models.user_dir_photo),
        ),
        migrations.AddField(
            model_name='vendor',
            name='photo',
            field=models.ImageField(default='image_not_found.jpg', upload_to=ecoshop.models.user_dir_photo),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
